# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket  = "kp-aws-vpc-terraform-statefiles"
        key     = "./terraform.tfstate"
        region  = "us-east-1"
        encrypt = true
    }
}
